---

- name: Installing RPMs for PostgreSQL version {{ PG_MAJOR }}
  become: yes
  yum:
    name: "{{ repositories.postgres }}/{{ PG_MAJOR }}/{{ ansible_distribution | lower }}/rhel-{{ ansible_distribution_version }}-{{ ansible_architecture }}/{{ item }}"
    state: present
  loop:
    - "postgresql{{ pg_major }}-libs-{{ PG_MAJOR }}.1{{ PG_MINOR }}-2PGDG.rhel{{ ansible_distribution_major_version }}.{{ ansible_architecture }}.rpm"
    - "postgresql{{ pg_major }}-{{ PG_MAJOR }}.1{{ PG_MINOR }}-2PGDG.rhel{{ ansible_distribution_major_version }}.{{ ansible_architecture }}.rpm"
    - "postgresql{{ pg_major }}-server-{{ PG_MAJOR }}.1{{ PG_MINOR }}-2PGDG.rhel{{ ansible_distribution_major_version }}.{{ ansible_architecture }}.rpm"





# Directory Link : /etc/alternatives
# Directory : /usr/pgsql-9.6
