---

- name: Delete group  "{{ group_name }}"
  become: yes
  group:
    name: "{{ group_name }}"
    state: absent
  register: groupDelete

- name: Delete Group Details
  debug:
    var: groupDelete
