---

- name: Step1 - Configure Repo for Maven
  become: yes
  get_url:
    url: "{{ repositories.maven }}"
    dest: '{{ yumDir }}/{{ yumRepos.maven }}'
    mode: 0644

- name: Step2 - Installing the Basic Packages
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ common_pks }}"
