---

- name: Installing the Basic Packages
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - maven
    - tree
    - httpd
    - telnet
    - git-core
    - wget
    - zip
    - unzip
