---

- name: Step1 - Configure Repo for Maven
  become: yes
  get_url:
    url: "{{ repositories.maven }}"
    dest: '{{ yumDir }}/{{ yumRepos.maven }}'
    mode: 0644

- name: Step2 - Installing the Basic Packages with specified version
  become: yes
  yum:
    name: "{{ item.value.name }}-{{ item.value.version }}*"
    state: present
  when: item.value.version != None
  loop: "{{ common_pks | dict2items }}"

- name: Step3 - Installing the Basic Packages with latest version
  become: yes
  yum:
    name: "{{ item.value.name }}"
    state: latest
  when: item.value.version == None
  loop: "{{ common_pks | dict2items }}"
