---

- name: Create/Make sure group  "{{ group_name }}" is present
  become: yes
  group:
    name: "{{ group_name }}"
    state: present
  register: groupCreation

- name: Group Detail
  debug:
    var: groupCreation
