---

- name: Creating user "{{ username }}" with admin access
  user: 
    name={{ username }}
    password={{ password | password_hash('sha512') }}
    groups={{ group_name }}
    append=yes
  when: assign_role == "yes"

- name: Creating users "{{ username }}" without admin access
  user: 
    name={{ username }}
    password={{ password | password_hash('sha512') }}
  when: assign_role == "no"

- name: Expiring password for user "{{ username }}"
  shell: 
    chage -d 0 "{{ username }}"

# Ref : https://thinkingmonster.wordpress.com/it-automation/386-2/ansible-roles/
