---

- name: Coping Local to Remote Hosts
  become: yes
  copy:
    src: "../{{ item }}"
    dest: "{{ scriptHomeDir }}/{{ scriptsDir }}"
    force: yes
    mode: 0744
  loop:
    - "{{ srcPythonDir }}"
    - "{{ srcServicesDir }}"
    - "{{ srcRepoDir }}"
  register: updatedServices

- name: Find the service files present
  become: yes
  find:
    paths: "{{ scriptHomeDir }}/{{ scriptsDir }}/{{ srcServicesDir }}"
    recurse: yes
    patterns: "*Initd"
  register: listOfServices

- name: Display the details of the service files
  debug:
    var: listOfServices

- name: Coping to "{{ initDirPer }}" path if RHEL-6
  become: yes
  copy:
    src: "{{ item.path }}"
    dest: "{{ initDir }}"
    force: yes
    mode: "{{ initDirPer }}"
    remote_src: true
  loop: "{{ listOfServices.files }}"
  #when: "{{ RHEL }}" == "6"

- name: Adding Files to the LIST
  vars:
    Files: []
  set_fact:
    Files: "{{ Files + [item.path | basename] }}"
  loop: "{{ listOfServices.files }}"

- name: Check files stored in list
  debug:
    var: Files

- name: Enable Chkconfig Services for automatic start
  become: yes
  service:
    name: "{{ item }}"
    enabled: yes
  loop: "{{ Files }}"
  register: addedServices

- name: Check files stored in list
  debug:
    var: addedServices
