---

- name: Step1 - Creating Directory for Temporary Downloads
  file:
    path: '{{ item }}'
    state: directory
    mode: 0775
  loop:
    - '{{ playbook_dir }}/packages'

- name: Step2 - Creating Scripts Directory
  become: yes
  file:
    path: '{{ item }}'
    state: directory
    mode: 0775
  loop:
    - /usr/local/sbin/custom-scripts

- name: Step3 - Download perl-Switch from rpmforge Repos
  get_url:
    url: ftp://ftp.pbone.net/mirror/apt.sw.be/redhat/7.3/en/i386/rpmforge/RPMS/perl-Switch-2.14-1.rh7.rf.noarch.rpm
    dest: '{{ playbook_dir }}/packages/perl-Switch-2.14-1.rh7.rf.noarch.rpm'
    mode: 0775

- name: Step4 -Installing Pre-Requestics for CW Metric Configuration
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - '{{ playbook_dir }}/packages/perl-Switch-2.14-1.rh7.rf.noarch.rpm'
    - perl-DateTime
    - perl-Sys-Syslog
    - perl-LWP-Protocol-https
    - perl-Digest-SHA
    - zip
    - unzip

- name: Step5 - Download and Unzip Monitoring Script from AWS
  become: yes
  unarchive:
    src: https://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.2.zip
    dest: /usr/local/sbin/custom-scripts/
    remote_src: True

- name: Step6 - Schedule cronjob for CloudWatch metric every 5mins
  become: yes
  cron:
    minute: '*/5'
    name: CloudWatch Custom Metric for every 5mins
    job: /usr/local/sbin/custom-scripts/aws-scripts-mon/aws-scripts-mon/mon-put-instance-data.pl --mem-used-incl-cache-buff --mem-util --disk-space-util --disk-path=/ --from-cron
    user: root
    state: present

- name: Step7 - Deleting Temporary Directory Created in Step1
  become: yes
  file:
    path: '{{ playbook_dir }}/packages'
    state: absent
    mode: 0775
