---

- name: Coping Local to Remote Hosts
  become: yes
  copy:
    src: "../{{ item }}"
    dest: "{{ scriptHomeDir }}/{{ scriptsDir }}"
    force: yes
    mode: 0744
    remote_src: yes
  loop:
    - "{{ srcPythonDir }}"
    - "{{ srcServicesDir }}"
    - "{{ srcRepoDir }}"
  register: updatedRepos
  when: type == "ansible"

- name: Installing Pre-Requestics for CW Metric Configuration for RHEL-8
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ RHEL_8_cw_pks }}"
  when: RHELver == "8"
  ignore_errors: yes

- name: Installing Pre-Requestics for CW Metric Configuration for RHEL-7
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ RHEL_7_cw_pks }}"
  when: RHELver == "7"
  ignore_errors: yes

- name: Installing Pre-Requestics for CW Metric Configuration for RHEL-6 - Preq for CPANM
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ RHEL_6_cw_pks }}"
  when: RHELver == "6"

- name: Installing Pre-Requestics for CW Metric Configuration for RHEL-6 - Installing CPANM
  shell:
    cmd: curl -L http://cpanmin.us | perl - --sudo App::cpanminus
    warn: False
  when: RHELver == "6"

- name: Installing Pre-Requestics for CW Metric Configuration for RHEL-6 - Installing Perl Modules
  become: yes
  cpanm:
    name: "{{ item }}"
  loop: "{{ RHEL_6_cpanm_pks }}"
  when: RHELver == "6"

- name: create dir
  file: 
    path: "{{ scriptHomeDir }}/{{ scriptsDir }}"
    state: directory

- name: Download and Unzip Monitoring Script from AWS
  become: yes
  unarchive:
    src: "{{ AWS_cw_script.url }}"
    dest: "{{ scriptHomeDir }}/{{ scriptsDir }}/"
    remote_src: True

- name: Schedule cronjob for CloudWatch Custom Metric - Every 5mins - Memory - Root
  become: yes
  cron:
    minute: '*/{{ AWS_cw_script.cw_cron }}'
    name: CloudWatch Custom Metric - Every 5mins - Memory - Root
    job: "{{ scriptHomeDir }}/{{ scriptsDir }}/{{ AWS_cw_script.dir }}/{{ AWS_cw_script.put_met }} --mem-used-incl-cache-buff --mem-util --disk-space-util --disk-path=/ --from-cron"
    user: root
    state: present

- name: Schedule cronjob for CloudWatch Custom Metric - Every 5mins - Disk
  become: yes
  cron:
    minute: '*/{{ AWS_cw_script.cw_cron }}'
    name: CloudWatch Custom Metric - Every 5mins - Disk - {{item.value.mount_point}}
    job: "{{ scriptHomeDir }}/{{ scriptsDir }}/{{ AWS_cw_script.dir }}/{{ AWS_cw_script.put_met }} --disk-space-util --disk-path={{item.value.mount_point}} --from-cron"
    user: root
    state: present
  loop: '{{ block_volumes.not_mounted | dict2items }}'

- name: Print CronJobs
  become: yes
  shell:
    cmd: cat /var/spool/cron/*
    warn: False
  register: crontab

- name: CW cron schedule output
  debug:
    var: crontab.stdout_lines

#Ref : https://stackoverflow.com/questions/42163232/using-cpanm-module-in-ansible
#Ref : https://metacpan.org/pod/App::cpanminus
