---

- name: Check MountPoint Folders
  become: yes
  file:
    path: '{{ item.value.mount_point }}'
    state: directory
    dest: '{{ item }}'
    mode: 0755
  loop: '{{ block_volumes.not_mounted | dict2items }}'

- name: Format New Volumes
  become: yes
  filesystem:
    fstype: xfs
    dev: '{{ item.value.mp_name }}'
  loop: '{{ block_volumes.not_mounted | dict2items }}'

- name: Format Exsisting Volumes
  become: yes
  filesystem:
    fstype: xfs
    dev: '{{ item.value.mp_name }}'
  loop: '{{ block_volumes.mounted | dict2items }}'
  ignore_errors: yes

- name: Mount BlockDevices
  become: yes
  mount:
    name: '{{ item.value.mount_point }}'
    src: '{{ item.value.mp_name }}'
    opts: noatime
    fstype: xfs
    state: mounted
  loop: '{{ block_volumes.not_mounted | dict2items }}'

- name: Format SWAP
  become: yes
  command: mkswap -f {{ block_volumes.swap.mp_name }}
  ignore_errors: yes

- name: Enable SWAP
  become: yes
  command: swapon {{ block_volumes.swap.mp_name }}
  ignore_errors: yes

- name: Add swap to fstab
  become: yes
  lineinfile:
    dest: /etc/fstab
    line: '{{ block_volumes.swap.mp_name }} swap swap defaults 0 0'
    state: present

- name: Current Time
  become: yes
  command: /bin/date +%s
  register: before_reboot

- name: Rebooting ...
  become: yes
  command: /sbin/shutdown now "Ansible-triggered Reboot"
  async: 0
  poll: 0
#  reboot:
#    reboot_timeout: 0
#  ignore_errors: yes

- name: Waiting "{{ ansible_ssh_host }}" to come back...
  local_action: wait_for host={{ ansible_ssh_host }} state=started delay=10 timeout=300

- name: Verify the reboot
  shell: (( `date +%s` - `awk -F . '{print $1}' /proc/uptime` > {{ before_reboot.stdout }} ))
