---

- name: Allow "{{ group_name }}" group to have passwordless sudo in /etc/sudoers
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    backup: yes
    regexp: '^%{{ group_name }}'
    line: '%{{ group_name }} ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s
  register: addSudoers

- name: Restart sshd service for new user to be added
  become: yes
  service:
    name: sshd
    state: reloaded
  register: serviceReload

- name: Add sudo Details
  debug:
    var: addSudoers

- name: SSHD Restart Status
  debug:
    msg:
      - SSHD - Current Status {{ serviceReload.status.SubState }}
      - SSHD - Stop    Status {{ serviceReload.status.ExecReload }}
      - SSHD - Start   Status {{ serviceReload.status.ExecStart }}
