---

- name: Allow "{{ group_name }}" group to have passwordless sudo in /etc/sudoers
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    backup: yes
    regexp: '^%{{ group_name }}'
    line: '%{{ group_name }} ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s
  register: addSudoers

- name: Sudo Details
  debug:
    var: addSudoers
