---

- name: Coping local to remote hosts
  become: yes
  copy:
    src: "{{ item }}"
    dest: "{{ scriptHomeDir }}/{{ scriptsDir }}"
    force: yes
    mode: 0744
  loop:
    - "{{ srcPythonDir }}"
    - "{{ srcServicesDir }}"

- name: Find the Service files
  become: yes
  find:
    paths: "{{ scriptHomeDir }}/{{ scriptsDir }}"
    recurse: yes
    patterns: "*Service"
  register: listOfServices

- name: check the content and structure of the variable listOfServices
  debug:
    var: listOfServices

- name: Coping to init.d path
  become: yes
  copy:
    src: "{{ item.path }}"
    dest: /etc/init.d
    force: yes
    mode: 0744
    remote_src: true
  loop: "{{ listOfServices.files }}"

- name: Enable services for automatic start
  become: yes
  sysvinit:
    name: "{{ item }}"
    enabled: no
  loop: "{{ listOfServices.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
