---

- name: Pre-Requisite for Jenkins
  debug:
    msg: All common packages must be installed

- name: Coping Local to Remote Hosts
  become: yes
  copy:
    src: "../{{ item }}"
    dest: "{{ scriptHomeDir }}/{{ scriptsDir }}"
    force: yes
    mode: 0744
  loop:
    - "{{ srcPythonDir }}"
    - "{{ srcServicesDir }}"
    - "{{ srcRepoDir }}"

- name: Find the repos files present
  become: yes
  find:
    paths: "{{ scriptHomeDir }}/{{ scriptsDir }}/{{ srcRepoDir }}"
    recurse: yes
    patterns: "jenkins*"
  register: listOfRepos

- name: Display the details of the repo files
  debug:
    var: listOfRepos.files

- name: Coping to "{{ yumDir }}" path
  become: yes
  copy:
    src: "{{ item.path }}"
    dest: "{{ yumDir }}"
    force: yes
    mode: 0644
    remote_src: true
  loop: "{{ listOfRepos.files }}"
  register: updatedRepos

- name: Replace JENKINS_REPO
  become: yes
  replace:
    path: "{{ yumDir }}/{{ item.path | basename }}"
    regexp: 'JENKINS_REPO'
    replace: '{{ repositories.jenkins.repo }}'
  loop: "{{ listOfRepos.files }}"

- name: Replace JENKINS_GPGKEY
  become: yes
  replace:
    path: "{{ yumDir }}/{{ item.path | basename }}"
    regexp: 'JENKINS_GPGKEY'
    replace: '{{ repositories.jenkins.gpgkey }}'
  loop: "{{ listOfRepos.files }}"

#- name: Import Jenkins Key
#  become: yes
#  rpm_key:
#    state: present
#    key: "{{ repositories.jenkins.gpgkey }}"

- name: Install Jenkins
  become: yes
  yum:
    name: jenkins
    state: present

- name: Start & Enable Jenkins
  become: yes
  systemd:
    name: jenkins
    state: started
    enabled: true

- name: Find my public ip
  uri:
    url: "{{ myPublicIP }}"
    return_content: yes
  register: publicIP
  
- name: Wait for Jenkins to start up
  uri:
    url: "http://{{ publicIP.content }}:8080"
    method: GET
    user: "{{ repositories.jenkins.user }}"
    password: "{{ repositories.jenkins.password }}"
    force_basic_auth: yes
    status_code: [200,401]
    timeout: 5
  register: jenkins_service_status
  # Keep on trying for 50 sec in 5 sec intervals
  retries: 5
  delay: 5
  until: >
    'status' in jenkins_service_status
    and
    ( jenkins_service_status['status'] == 200 or jenkins_service_status['status'] == 401 )

- name: Display the Jenkins URL
  debug:
    msg: Jenkins URL is - http://{{ publicIP.content }}:8080

- name: Read file
  become: yes
  slurp:
    src: "{{ repositories.jenkins.pwd }}"
  register: paswordFile

- name: Initial Password is
  debug:
    msg: "{{ paswordFile['content'] | b64decode }}"
