---

- name: Un-Installing RPMs matches postgresql
  become: yes
  yum:
    name: "{{ item }}*"
    state: absent
  loop:
    - "postgresql{{ pg_major }}-libs-{{ PG_MAJOR }}"
    - "postgresql{{ pg_major }}-{{ PG_MAJOR }}"
    - "postgresql{{ pg_major }}-server-{{ PG_MAJOR }}"
