---

- name: Separate facts
  set_fact:
    py_executable: "{{ py_executables.split(',') }}"

- name: Installing Python Modules
  become: True
  pip:
    name: "{{ item[0] }}"
    executable: "{{ item[1] }}"
    umask: "0022"
    state: present
  with_nested:
    - "{{ pyModules }}"
    - "{{ py_executable }}"
  ignore_errors: yes
