---

application             : postgres
application_user        : postgres
application_user_group  : postgres_grp
appplication_port       : 5432
company                 : MIT

scriptHomeDir           : /usr/local/sbin
scriptsDir              : custom-scripts
logsDir                 : logs
rpmDir                  : rpms
srcPythonDir            : ../python/
srcServicesDir          : ../services/

common_pks              : ['maven' , 'tree' , 'httpd' , 'telnet' , 'git-core' , 'wget' , 'zip' , 'unzip' , 'java-1.8.0-openjdk' ]
RHEL_8_cw_pks           : ['ftp://ftp.pbone.net/mirror/apt.sw.be/redhat/7.3/en/i386/rpmforge/RPMS/perl-Switch-2.14-1.rh7.rf.noarch.rpm','ftp://ftp.pbone.net/mirror/apt.sw.be/redhat/7.3/en/i386/rpmforge/RPMS/perl-DateTime-0.4305-1.rh7.rf.i386.rpm','perl-Sys-Syslog','perl-LWP-Protocol-https','perl-Digest-SHA','perl-devel']
RHEL_7_cw_pks           : ['ftp://ftp.pbone.net/mirror/apt.sw.be/redhat/7.3/en/i386/rpmforge/RPMS/perl-Switch-2.14-1.rh7.rf.noarch.rpm','perl-DateTime','perl-Sys-Syslog','perl-LWP-Protocol-https','perl-Digest-SHA','perl-devel']
RHEL_6_cw_pks           : ['perl-DateTime' , 'perl-CPAN' , 'perl-Net-SSLeay' , 'perl-IO-Socket-SSL' , 'perl-Digest-SHA' , 'gcc' , 'perl-devel']
RHEL_6_cpanm_pks        : ['YAML' , 'LWP::Protocol::https' , 'Sys::Syslog' , 'Switch']

repositories  :
  pip         : https://bootstrap.pypa.io/get-pip.py
  epel_8      : https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
  epel_7      : https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  epel_6      : https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
  maven       : http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo
  hashicorp   : https://releases.hashicorp.com
  jenkins     : 
    repo      : http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    gpgkey    : https://jenkins-ci.org/redhat/jenkins-ci.org.key
    pwd       : /var/lib/jenkins/secrets/initialAdminPassword
    plugins   : ['rebuild' , 'github-pullrequest' , 'claim' , 'view-job-filters' , 'nested-view' , 'job-import-plugin' , 'plugin-usage-plugin' , 'disk-usage' , 'greenballs' , 'embeddable-build-status' , 'job-restrictions' , 'mask-passwords' , 'ansible' , 'ansicolor' , 'build-timeout' , 'workflow-aggregator' , 'terraform' , 'job-dsl' , 'xml-job-to-job-dsl' , 'thinBackup']
    user      : admin
    password  : admin

worldAccess   : /usr/bin/
yumDir        : /etc/yum.repos.d
yumRepos  :
  maven   : epel-maven.repo
  jenkins : jenkins.repo

AWS_cw_script : 
  url         : https://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.2.zip
  dir         : aws-scripts-mon
  get_met     : mon-get-instance-stats.pl
  put_met     : mon-put-instance-data.pl
  cw_cron     : 5

block_volumes :
  mounted     :
    root      :
      mount_point : /
      mp_name     : /dev/xvda
  not_mounted :
    home      :
      mp_name     : /dev/xvdb
      mount_point : /home
    audit     :
      mp_name     : /dev/xvdc
      mount_point : /var/log/audit
  swap        :
    mp_name       : /dev/xvdd
