---

application		        : postgres
application_user	    : postgres
application_user_group	: postgres_grp
appplication_port	    : 5432
company			        : MIT

scriptHomeDir           : /usr/local/sbin
scriptsDir              : custom-scripts
logsDir                 : logs
rpmDir                  : rpms
srcPythonDir            : ../python/
srcServicesDir          : ../services/

serviceFiles		: ['updateSSHSudoersService']

block_volumes	:
  mounted		:
    root			:
      mount_point	: /
      mp_name		: /dev/xvda
  not_mounted	:
    home		:
      mp_name		: /dev/xvdb
      mount_point	: /home
    audit		:
      mp_name		: /dev/xvdc
      mount_point	: /var/log/audit
  swap			:
    mp_name			: /dev/xvdd
