---

application		        : postgres
application_user	    : postgres
application_user_group	: postgres_grp
appplication_port	    : 5432
company			        : MIT

scriptHomeDir           : /usr/local/sbin
scriptsDir              : custom-scripts
logsDir                 : logs
rpmDir                  : rpms
srcPythonDir            : ../python/
srcServicesDir          : ../services/

AWS_cw_script           : 
  url     : https://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.2.zip
  dir     : aws-scripts-mon
  get_met : mon-get-instance-stats.pl
  put_met : mon-put-instance-data.pl
common_pks              : ['zip','unzip']
RHEL_7_cw_pks           : ['ftp://ftp.pbone.net/mirror/apt.sw.be/redhat/7.3/en/i386/rpmforge/RPMS/perl-Switch-2.14-1.rh7.rf.noarch.rpm','perl-DateTime','perl-Sys-Syslog','perl-LWP-Protocol-https','perl-Digest-SHA','perl-devel']
RHEL_6_cw_pks		: ['perl-DateTime','perl-CPAN','perl-Net-SSLeay','perl-IO-Socket-SSL','perl-Digest-SHA','gcc','perl-devel']
RHEL_6_cpanm_pks        : ['YAML','LWP::Protocol::https','Sys::Syslog','Switch']

block_volumes	:
  mounted		:
    root			:
      mount_point	: /
      mp_name		: /dev/xvda
  not_mounted	:
    home		:
      mp_name		: /dev/xvdb
      mount_point	: /home
    audit		:
      mp_name		: /dev/xvdc
      mount_point	: /var/log/audit
  swap			:
    mp_name			: /dev/xvdd
