---

application             : postgres
application_user        : postgres
application_user_group  : postgres_grp
appplication_port       : 5432
company                 : MIT

scriptHomeDir           : /usr/local/sbin
scriptsDir              : custom-scripts
logsDir                 : logs
rpmDir                  : rpms
srcPythonDir            : python
srcServicesDir          : services
srcRepoDir              : yum-repos-d

common_pks              : 
  maven     :
    name    : apache-maven
    version : 
  tree      :
    name    : tree
    version : 1.6.0
  telnet    :
    name    : telnet
    version :
  git-core  :
    name    : git
    version :
  wget      :
    name    : wget
    version :
  zip       :
    name    : zip
    version :
  unzip     :
    name    : unzip
    version :
  java      :
    name    : java-1.8.0-openjdk
    version :
  py2-pip   :
    name    : python2-pip
    version : 
  python3   :
    name    : python3
    version : 
  py3-pip   :
    name    : python3-pip
    version : 

RHEL_8_cw_pks           : ['ftp://ftp.pbone.net/mirror/apt.sw.be/redhat/7.3/en/i386/rpmforge/RPMS/perl-Switch-2.14-1.rh7.rf.noarch.rpm','ftp://ftp.pbone.net/mirror/apt.sw.be/redhat/7.3/en/i386/rpmforge/RPMS/perl-DateTime-0.4305-1.rh7.rf.i386.rpm','perl-Sys-Syslog','perl-LWP-Protocol-https','perl-Digest-SHA','perl-devel']
RHEL_7_cw_pks           : ['ftp://ftp.pbone.net/mirror/apt.sw.be/redhat/7.3/en/i386/rpmforge/RPMS/perl-Switch-2.14-1.rh7.rf.noarch.rpm','perl-DateTime','perl-Sys-Syslog','perl-LWP-Protocol-https','perl-Digest-SHA','perl-devel']
RHEL_6_cw_pks           : ['perl-DateTime' , 'perl-CPAN' , 'perl-Net-SSLeay' , 'perl-IO-Socket-SSL' , 'perl-Digest-SHA' , 'gcc' , 'perl-devel']
RHEL_6_cpanm_pks        : ['YAML' , 'LWP::Protocol::https' , 'Sys::Syslog' , 'Switch']

repositories  :
  pip         : https://bootstrap.pypa.io/get-pip.py
#  epel_8      : https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
#  epel_7      : https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
#  epel_6      : https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
  epel        : 
    repo      : https://dl.fedoraproject.org/pub/epel/
    gpgurl    : RPM-GPG-KEY-EPEL-
    gpgkey    : RPM-GPG-KEY-EPEL-
  maven       : http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo
  hashicorp   : https://releases.hashicorp.com
  postgres    : https://download.postgresql.org/pub/repos/yum
  jenkins     : 
    repo      : https://pkg.jenkins.io/redhat/
    gpgurl    : jenkins.io.key
    gpgkey    : RPM-GPG-KEY-JENKINS
    pwd       : /var/lib/jenkins/secrets/initialAdminPassword
    plugins   : ['rebuild' , 'github-pullrequest' , 'claim' , 'view-job-filters' , 'nested-view' , 'job-import-plugin' , 'plugin-usage-plugin' , 'disk-usage' , 'greenballs' , 'embeddable-build-status' , 'job-restrictions' , 'mask-passwords' , 'ansible' , 'ansicolor' , 'build-timeout' , 'workflow-aggregator' , 'terraform' , 'job-dsl' , 'xml-job-to-job-dsl' , 'thinBackup']
    user      : admin
    password  : admin

pyModules     : ['ansible', 'argparse', 'babel', 'backports.ssl-match-hostname', 'cffi', 'chardet', 'cloud-init', 'configobj', 'cryptography', 'decorator', 'email', 'enum34', 'ethtool', 'gitdb', 'gitpython', 'httplib2', 'idna', 'iniparse', 'ipaddr', 'ipaddress', 'ipy', 'javapackages', 'jenkinsapi', 'jinja2', 'jmespath', 'jsonpatch', 'jsonpointer', 'kitchen', 'logging', 'lxml', 'm2crypto', 'magic-file-extensions', 'markupsafe', 'paramiko', 'pciutils', 'perf', 'pip', 'ply', 'policycoreutils-default-encoding', 'prettytable', 'psycopg2-binary', 'ptable', 'pyasn1', 'pycparser', 'pycurl', 'pygobject', 'pygpgme', 'pyinotify', 'pyliblzma', 'pyopenssl', 'pyserial', 'python', 'python-dateutil', 'python-dmidecode', 'python-linux-procfs', 'pytz', 'pyudev', 'pyxattr', 'pyyaml', 'requests', 'rhnlib', 'schedutils', 'seobject', 'sepolicy', 'setuptools', 'six', 'smmap', 'subscription-manager', 'syspurpose', 'urlgrabber', 'urllib3', 'wsgiref', 'yum-metadata-parser']

myPublicIP    : http://ifconfig.me/ip 
GPG_KEY_Dir   : /etc/pki/rpm-gpg/
worldAccess   : /usr/bin/
yumDir        : /etc/yum.repos.d
yumDirPer     : '0644'
initDir       : /etc/init.d
initDirPer    : '0754'
systemdDir    : /etc/systemd/system
systemdDirPer : '0754'
pythonPer     : '0754'

yumRepos  :
  maven   : epel-maven.repo
  jenkins : jenkins.repo

AWS_cw_script : 
  url         : https://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.2.zip
  dir         : aws-scripts-mon
  get_met     : mon-get-instance-stats.pl
  put_met     : mon-put-instance-data.pl
  cw_cron     : 5

block_volumes :
  mounted     :
    root      :
      mount_point : /
      mp_name     : /dev/xvda
  not_mounted :
    home      :
      mp_name     : /dev/xvdb
      mount_point : /home
    audit     :
      mp_name     : /dev/xvdc
      mount_point : /var/log/audit
  swap        :
    mp_name       : /dev/xvdd
