---

- name: Deleting User "{{ username }}"
  become: yes
  user:
    name: "{{ username }}"
    state: absent
    remove:  yes
  register: deleteUser

- name: Delete User Details
  debug:
    var: deleteUser
