---

- name: Step1 -Remove  Schedule cronjob for CloudWatch metric every 5mins
  become: yes
  cron:
    minute: '*/{{ AWS_cw_script.cw_cron }}'
    name: CloudWatch Custom Metric for every 5mins
    job: "{{ scriptHomeDir }}/{{ scriptsDir }}/{{ AWS_cw_script.dir }}/{{ AWS_cw_script.put_met }} --mem-used-incl-cache-buff --mem-util --disk-space-util --disk-path=/ --from-cron"
    user: root
    state: absent

- name: Print CronJobs
  shell:
    cmd: cat /var/spool/cron/*
    warn: False
  register: crontab

- name: CW cron schedule output
  debug:
    var: crontab.stdout_lines
