---

- hosts: 127.0.0.1
  connection: localhost

- hosts: 127.0.0.1
  vars_files:
    - 'vars/vars.yml'

  roles:
    - { role: install_pgsql_client,         tags: ['pgsql_install']		    }
    - { role: install_list_of_packages,		tags: ['list_install']		    }
    - { role: install_packer_package,		tags: ['packer_install']	    }
    - { role: install_terraform_package,	tags: ['terraform_install']	    }
    - { role: uninstall_pgsql_client,		tags: ['pgsql_uninstall']	    }
    - { role: uninstall_list_of_packages,	tags: ['list_uninstall']	    }
    - { role: uninstall_packer_package,		tags: ['packer_uninstall']	    }
    - { role: uninstall_terraform_package,	tags: ['terraform_uninstall']	}
    - { role: create_user,  password: “{{ user_password }}”,    username: “{{ user_name }}”,    assigned_role: “{{ is_root }}”, when: action == “create_user” }
    - { role: delete_user,  username: “{{ user_name }}”,        when: action == “delete_user” }
