---

- name: Step1 - Un-Installing the Basic Packages
  become: yes
  yum:
    name: "{{ item }}"
    state: absent
  loop: "{{ common_pks.keys() }}"
  register: listUnInstall

- name: Output for list Un-Install
  debug:
    msg: Message - {{ listUnInstall.msg }}
