---

- name:	Download and Unzip Packer package from Hashicorp
  become: yes
  unarchive:
    src: https://releases.hashicorp.com/packer/1.5.1/packer_1.5.1_linux_amd64.zip
    dest: /usr/bin/
    remote_src: True
