---

- name: Remove "{{ group_name }}" group from sudoers in /etc/sudoers
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: absent
    backup: yes
    regexp: '^%{{ group_name }}'
    line: '%{{ group_name }} ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s
  register: remSudoers

- name: Restart sshd service for new user to be added
  service:
    name: sshd
    state: reloaded
  register: serviceReload

- name: Remove sudo Details
  debug:
    var: remSudoers

- name: SSHD Restart Status
  debug:
    msg: 
      - SSHD - Current Status {{ serviceReload.status.SubState }}
      - SSHD - Stop    Status {{ serviceReload.status.ExecReload }}
      - SSHD - Start   Status {{ serviceReload.status.ExecStart }}
