---

- name: Download and Unzip Terraform package form Hashicrop
  become: yes
  unarchive:
    src: "{{repositories.hashicorp }}/terraform/{{ tfVersion }}/terraform_{{ tfVersion }}_linux_amd64.zip"
    dest: "{{ worldAccess }}"
    remote_src: True
  register: tfInstall

- name: Output of Terraform installation
  debug:
    var: tfInstall

